### ISSUE TITLE
Fails to Load on 1.21.2/3

### ISSUE THREAD

**Issue by BenguMC** [Ancientkingg/fancyPants#16]
EDIT: As noted in replies, it seems the best practice is to use the newest 1.21.2/3 features and not use this shader on newest versions.

Newest update breaks the shaders. Here is the error dump from client log when you load the pack.

[11:06:12] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_entity_translucent (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_entity_translucent (VERTEX)
 - minecraft:core/rendertype_armor_cutout_no_cull (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_armor_cutout_no_cull (VERTEX)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at awb.a(SourceFile:68) ~[1.21.3.jar:?]
	at bry.d(SourceFile:164) ~[1.21.3.jar:?]
	at bsc.d(SourceFile:23) ~[1.21.3.jar:?]
	at bry.B(SourceFile:138) ~[1.21.3.jar:?]
	at bry.bA(SourceFile:123) ~[1.21.3.jar:?]
	at fmg.c(SourceFile:1307) [1.21.3.jar:?]
	at fmg.f(SourceFile:933) [1.21.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [1.21.3.jar:?]
Caused by: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_entity_translucent (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_entity_translucent (VERTEX)
 - minecraft:core/rendertype_armor_cutout_no_cull (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_armor_cutout_no_cull (VERTEX)
	at gmc.a(SourceFile:174) ~[1.21.3.jar:?]
	at gmc.a(SourceFile:37) ~[1.21.3.jar:?]
	at awa.a(SourceFile:14) ~[1.21.3.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 9 more

**Comment by Patbox** [comment]
You probably should no longer use this shader, as vanilla now supports custom armor textures. Fo other uses, update would still be needed

**Comment by BenguMC** [comment]
> You probably should no longer use this shader, as vanilla now supports custom armor textures. Fo other uses, update would still be needed

I am not aware of any vanilla custom armor textures... Can you link anything? I have not seen anything of the sort, unless you're talking about trims?

**Comment by Patbox** [comment]
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21-2
Search for `minecraft:equipable` and `Custom Equipment Layers`

**Comment by BenguMC** [comment]
> https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21-2 Search for `minecraft:equipable` and `Custom Equipment Layers`

Thank you very much. I will work with this going forward. :)

**Comment by Ancientkingg** [comment]
> You probably should no longer use this shader, as vanilla now supports custom armor textures. Fo other uses, update would still be needed

I definitely agree with this advice. If possible avoid shaders, since they carry a lot of baggage. There are however some niche use cases in which fancyPants can still be useful.
